/* Umber - Stable C ABI (generated by cbindgen).
 *
 * DO NOT EDIT BY HAND. Regenerate with:
 *     cbindgen --config umber-ffi/cbindgen.toml --crate umber-ffi -o umber-ffi/include/umber.h
 *
 * Shape contract: umber-ffi/src/lib.rs module docs (总案 §41.6 §50).
 * All strings are UTF-8 with explicit length. Ownership of event JSON
 * transfers to the caller on delivery; free it with runtime_string_free.
 */

#ifndef UMBER_H
#define UMBER_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define RUNTIME_ABI_MAJOR 0

#define RUNTIME_ABI_MINOR 2

#define UMER_OK 0

#define UMER_ERR_NULL_ARGUMENT -1

#define UMER_ERR_ABI_MISMATCH -2

#define UMER_ERR_OPEN_FAILED -3

#define UMER_ERR_INTERNAL -4

/**
 * `runtime_stream_open` 的目标 Deployment 未配置（且未开启 demo）。
 */
#define UMER_ERR_NOT_CONFIGURED -5

/**
 * Catalog 读取 / 解析 / 格式版本校验失败。
 */
#define UMER_ERR_CATALOG -6

/**
 * `runtime_stream_next` / `runtime_status` 状态：数据已交付。
 */
#define UMER_EVENT 1

/**
 * 流已终结（终结合成事件已在之前交付）。
 */
#define UMER_CLOSED 2

/**
 * 等待超时，流可能仍有后续事件。
 */
#define UMER_WOULD_BLOCK 3

typedef struct UmerRuntime UmerRuntime;

typedef struct UmerStream UmerStream;

/**
 * C 侧数据载体。`json` 为 UTF-8，调用方必须用 `runtime_string_free` 释放。
 *
 * `runtime_stream_next` 用它交付事件；`runtime_status` 用它交付运行时状态。
 */
typedef struct UmerEvent {
  uint64_t sequence;
  char *json;
  size_t json_len;
} UmerEvent;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * ABI 版本：(major << 16) | minor。宿主必须校验 major 一致（总案 §50.3）。
 */
uint32_t runtime_abi_version(void);

/**
 * 创建 Runtime 实例。返回 NULL 表示失败。
 *
 * 新实例**没有**任何已配置的 Deployment，demo 关闭：
 * 必须先 `runtime_set_deployment` 或 `runtime_set_demo`。
 *
 * # Safety
 *
 * 返回的句柄必须且只能通过 `runtime_shutdown` 释放一次。
 * 句柄可被任意线程使用（内部状态加锁）。
 */
struct UmerRuntime *runtime_init(void);

/**
 * 销毁 Runtime 实例。NULL 安全。
 *
 * # Safety
 *
 * `rt` 必须是 `runtime_init` 返回且未销毁过的句柄；销毁后不得再使用
 * （包括传给本函数）。不得与仍在使用的流句柄并发调用。
 */
void runtime_shutdown(struct UmerRuntime *rt);

/**
 * 开启 / 关闭内置 demo 事件源（默认关闭）。
 *
 * demo 流是**假数据**，只用于验证 ABI 形态，不连接任何 Provider。
 * 未开启且未配置部署时 `runtime_stream_open` 返回
 * `UMER_ERR_NOT_CONFIGURED`。
 *
 * # Safety
 *
 * `rt` 必须是有效的 Runtime 句柄。线程安全。
 */
int32_t runtime_set_demo(struct UmerRuntime *rt, int32_t enabled);

/**
 * 注册（或覆盖）一个 Deployment。JSON 形状见本文件 `DeploymentConfig` 文档。
 *
 * 同一个 `id` 重复调用即覆盖。成功返回 `UMER_OK`；
 * JSON 不合法或 `len` 与 C 字符串长度不一致返回 `UMER_ERR_OPEN_FAILED`。
 *
 * # Safety
 *
 * `rt` 必须是有效的 Runtime 句柄；`config_json` 必须指向至少 `len`
 * 字节可读的 UTF-8 内存。线程安全。
 */
int32_t runtime_set_deployment(struct UmerRuntime *rt, const char *config_json, size_t len);

/**
 * 写入一条凭据到 Runtime 的内存凭据存储。
 *
 * **Runtime 不持久化密钥**：进程退出即丢失。需要持久化的宿主应自己落到
 * 系统钥匙串（见 `docs/HOST_INTEGRATION.md` §4），启动时再写入本函数。
 * 密钥绝不进入日志、Catalog 或 Canonical Request。
 *
 * # Safety
 *
 * `rt` 必须是有效的 Runtime 句柄；`reference` / `secret` 必须是以 NUL
 * 结尾的 UTF-8 C 字符串。线程安全。
 */
int32_t runtime_set_credential(struct UmerRuntime *rt, const char *reference, const char *secret);

/**
 * 加载 Canonical Catalog（模型知识：能力 / 上下文 / 价格）。
 *
 * 接受裸 Catalog 或 `model-data build` 的构建产物；
 * `format_version` 不在兼容区间内即拒绝。
 * **完全离线可用**——Catalog 是随包分发物，不是运行时网络依赖。
 *
 * # Safety
 *
 * `rt` 必须是有效的 Runtime 句柄；`path` 必须是以 NUL 结尾的 UTF-8
 * C 字符串路径。线程安全。
 */
int32_t runtime_load_catalog(struct UmerRuntime *rt, const char *path);

/**
 * 读取运行时状态（JSON），用于宿主自检与排查。
 *
 * 形状：
 *
 * ```json
 * {"abi":"0.2","deployments":1,"catalog_loaded":true,"catalog_entries":3230,
 *  "demo_fallback":false,"configured_models":["dep-1"]}
 * ```
 *
 * 交付的 JSON 归调用方所有，必须用 `runtime_string_free` 释放；
 * 成功返回 `UMER_EVENT`。
 *
 * # Safety
 *
 * `rt` 必须是有效的 Runtime 句柄；`out` 必须指向可写的 `CUmerEvent`。
 * 线程安全。
 */
int32_t runtime_status(struct UmerRuntime *rt, struct UmerEvent *out);

/**
 * 打开一次 Invocation 流。
 *
 * `request_json` 是 Canonical GenerateRequest 的 UTF-8 JSON；
 * 形态校验失败返回 `UMER_ERR_OPEN_FAILED`。
 *
 * 路由（0.2）：`request.model` 命中已注册的 Deployment → 真实协议链路；
 * 否则若 `runtime_set_demo(rt, 1)` → demo 流；否则
 * `UMER_ERR_NOT_CONFIGURED`。
 *
 * # Safety
 *
 * - `rt` 必须是有效的 Runtime 句柄；`request_json` 必须指向至少 `len`
 *   字节可读内存；`out` 必须指向可写指针。
 * - 成功时 `*out` 收到新句柄，须用 `runtime_stream_close` 释放恰好一次。
 * - 线程安全：可从任意线程调用；每个流句柄同一时刻只应被一个线程拉取。
 */
int32_t runtime_stream_open(struct UmerRuntime *rt,
                            const char *request_json,
                            size_t len,
                            struct UmerStream **out);

/**
 * 拉取下一个事件（阻塞至多 `timeout_ms`）。
 *
 * 事件 JSON 的所有权转移到调用方，用 `runtime_string_free` 释放；
 * `UMER_WOULD_BLOCK` 表示超时但流未关闭，可继续拉取。
 *
 * # Safety
 *
 * - `stream` 必须是 `runtime_stream_open` 产出且未关闭的句柄。
 * - `out` 必须指向可写的 `CUmerEvent`；成功时其 `json` 字段由本函数
 *   分配，调用方必须用 `runtime_string_free` 释放恰好一次。
 * - 线程安全：同一流句柄不得被两个线程同时拉取。
 */
int32_t runtime_stream_next(struct UmerStream *stream, uint32_t timeout_ms, struct UmerEvent *out);

/**
 * 请求取消。取消语义由 Runtime Invocation 承载（总案 §25）；
 * 已关闭的流返回 OK。
 *
 * # Safety
 *
 * `stream` 必须是有效或 NULL 的流句柄。线程安全：可与
 * `runtime_stream_next` 并发调用（这是取消期间的标准用法）。
 */
int32_t runtime_stream_cancel(struct UmerStream *stream);

/**
 * 关闭并回收流。NULL 安全；关闭后流句柄不可再用。
 *
 * # Safety
 *
 * `stream` 必须是 `runtime_stream_open` 产出且未被关闭过的句柄，
 * 或为 NULL。关闭会等待内部 worker 结束；调用方必须保证没有其他线程
 * 仍在本流句柄上阻塞于 `runtime_stream_next`。
 */
void runtime_stream_close(struct UmerStream *stream);

/**
 * 释放本 ABI 交付的 JSON（`runtime_stream_next` / `runtime_status`）。
 * NULL 安全。
 *
 * # Safety
 *
 * `ptr` 必须是本 ABI 分配且尚未释放的指针，或为 NULL。
 * 不得释放任何其他来源的指针。
 */
void runtime_string_free(char *ptr);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* UMBER_H */
