/* Universal Embedded Model Runtime - Stable C ABI (generated by cbindgen).
 *
 * DO NOT EDIT BY HAND. Regenerate with:
 *     cbindgen --config runtime-ffi/cbindgen.toml --crate runtime-ffi -o runtime-ffi/include/umer.h
 *
 * Shape contract: runtime-ffi/src/lib.rs module docs (总案 §41.6 §50).
 * All strings are UTF-8 with explicit length. Ownership of event JSON
 * transfers to the caller on delivery; free it with runtime_string_free.
 */

#ifndef UMER_H
#define UMER_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define RUNTIME_ABI_MAJOR 0

#define RUNTIME_ABI_MINOR 1

#define UMER_OK 0

#define UMER_ERR_NULL_ARGUMENT -1

#define UMER_ERR_ABI_MISMATCH -2

#define UMER_ERR_OPEN_FAILED -3

#define UMER_ERR_INTERNAL -4

/**
 * `runtime_stream_next` 状态：事件已交付。
 */
#define UMER_EVENT 1

/**
 * 流已终结（终结合成事件已在之前交付）。
 */
#define UMER_CLOSED 2

/**
 * 等待超时，流可能仍有后续事件。
 */
#define UMER_WOULD_BLOCK 3

typedef struct UmerRuntime UmerRuntime;

typedef struct UmerStream UmerStream;

/**
 * C 侧事件结构。`json` 为 UTF-8，调用方必须用 `runtime_string_free` 释放。
 */
typedef struct UmerEvent {
  uint64_t sequence;
  char *json;
  size_t json_len;
} UmerEvent;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * ABI 版本：(major << 16) | minor。宿主必须校验 major 一致（总案 §50.3）。
 */
uint32_t runtime_abi_version(void);

/**
 * 创建 Runtime 实例。返回 NULL 表示失败。
 *
 * # Safety
 *
 * 返回的句柄必须且只能通过 `runtime_shutdown` 释放一次。
 * 句柄可被任意线程使用；`UmerRuntime` 本身不暴露字段。
 */
struct UmerRuntime *runtime_init(void);

/**
 * 销毁 Runtime 实例。NULL 安全。
 *
 * # Safety
 *
 * `rt` 必须是 `runtime_init` 返回且未销毁过的句柄；销毁后不得再使用
 * （包括传给本函数）。不得与仍在使用的流句柄并发调用。
 */
void runtime_shutdown(struct UmerRuntime *rt);

/**
 * 打开一次 Invocation 流。
 *
 * `request_json` 是 Canonical GenerateRequest 的 UTF-8 JSON；
 * 形态校验失败返回 `UMER_ERR_OPEN_FAILED`。
 *
 * # Safety
 *
 * - `rt` 必须是有效的 Runtime 句柄；`request_json` 必须指向至少 `len`
 *   字节可读内存；`out` 必须指向可写指针。
 * - 成功时 `*out` 收到新句柄，须用 `runtime_stream_close` 释放恰好一次。
 * - 线程安全：可从任意线程调用；每个流句柄同一时刻只应被一个线程拉取。
 */
int32_t runtime_stream_open(struct UmerRuntime *rt,
                            const char *request_json,
                            size_t len,
                            struct UmerStream **out);

/**
 * 拉取下一个事件（阻塞至多 `timeout_ms`）。
 *
 * 事件 JSON 的所有权转移到调用方，用 `runtime_string_free` 释放；
 * `UMER_WOULD_BLOCK` 表示超时但流未关闭，可继续拉取。
 *
 * # Safety
 *
 * - `stream` 必须是 `runtime_stream_open` 产出且未关闭的句柄。
 * - `out` 必须指向可写的 `CUmerEvent`；成功时其 `json` 字段由本函数
 *   分配，调用方必须用 `runtime_string_free` 释放恰好一次。
 * - 线程安全：同一流句柄不得被两个线程同时拉取。
 */
int32_t runtime_stream_next(struct UmerStream *stream, uint32_t timeout_ms, struct UmerEvent *out);

/**
 * 请求取消。取消语义由 Runtime Invocation 承载（总案 §25）；
 * 已关闭的流返回 OK。
 *
 * # Safety
 *
 * `stream` 必须是有效或 NULL 的流句柄。线程安全：可与
 * `runtime_stream_next` 并发调用（这是取消期间的标准用法）。
 */
int32_t runtime_stream_cancel(struct UmerStream *stream);

/**
 * 关闭并回收流。NULL 安全；关闭后流句柄不可再用。
 *
 * # Safety
 *
 * `stream` 必须是 `runtime_stream_open` 产出且未被关闭过的句柄，
 * 或为 NULL。关闭会等待内部 worker 结束；调用方必须保证没有其他线程
 * 仍在本流句柄上阻塞于 `runtime_stream_next`。
 */
void runtime_stream_close(struct UmerStream *stream);

/**
 * 释放 `runtime_stream_next` 交付的事件 JSON。NULL 安全。
 *
 * # Safety
 *
 * `ptr` 必须是 `runtime_string_free` 尚未释放过的、由本 ABI 分配的
 * 指针，或为 NULL。不得释放任何其他来源的指针。
 */
void runtime_string_free(char *ptr);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* UMER_H */
